[FIX] cetmix_tower_server:t3960 Fix replacing of variables after create server from template
cetmix/cetmix-tower pull request #100
Opened 2024-10-01 08:42 UTC by GabbasovDinar

2024-10-01 11:55 UTC, ivs-cetmix commented
/ocabot rebase

2024-10-01 11:55 UTC, CetmixGitDrone commented
Congratulations, PR rebased to [14.0-dev](https://github.com/cetmix/cetmix-tower/commits/14.0-dev).

2024-10-07 09:40 UTC, ivs-cetmix requested changes
Consider adding the following test scenario:

- Variable A is defined in the  Server Template == "pizza"
- Variable B is defined in the  Server Template == "green"


New server is created from the template with the following variable values:

- Variable B  == "green"
- Variable C == "dog"

Expected result is: new server is created with the following variable values:

- Variable A == "pizza"
- Variable B  == "green"
- Variable C == "dog"

2024-10-07 10:58 UTC, GabbasovDinar commented
> Consider adding the following test scenario:
> 
> * Variable A is defined in the  Server Template == "pizza"
> * Variable B is defined in the  Server Template == "green"
> 
> New server is created from the template with the following variable values:
> 
> * Variable B  == "green"
> * Variable C == "dog"
> 
> Expected result is: new server is created with the following variable values:
> 
> * Variable A == "pizza"
> * Variable B  == "green"
> * Variable C == "dog"

Fixed. 

P.S. I used exists variables for such case

2024-10-07 13:27 UTC, ivs-cetmix requested changes

2024-10-07 13:27 UTC, ivs-cetmix commented on cetmix_tower_server/tests/test_server_template.py
> +                self.variable_version.name: "test server version",
We use `reference` field here not `name`

2024-10-07 15:13 UTC, ivs-cetmix approved these changes
Code review LGTM

2024-10-07 16:00 UTC, CetmixGitDrone commented
This PR has the `approved` label and has been created more than 5 days ago. It should therefore be ready to merge by a maintainer (or a PSC member if the concerned addon has no declared maintainer). 🤖

2024-10-07 16:35 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-10-07 16:35 UTC, CetmixGitDrone commented
This PR looks fantastic, let's merge it!
Prepared branch [14.0-dev-ocabot-merge-pr-100-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-100-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-10-07 16:37 UTC, merged

2024-10-07 16:37 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at 50c240f9c4b628043fddaf76ee5e4d84c30866a1. Thanks a lot for contributing to cetmix. ❤️