[14.0][ADD] cetmix_tower_server_yaml Yaml support for Cetmix Tower
cetmix/cetmix-tower pull request #103
Opened 2024-10-08 15:38 UTC by ivs-cetmix

This module implements YAML export/import for Cetmix Tower.

Following features are added in this PR:

- Save Command as yaml
- Populate Command values from yaml

Please check the module documentation for more details.

2024-10-08 16:08 UTC, ivs-cetmix commented
Hi @norlinhenrik does this look like something you were asking for? Would appreciate your intermediate review in any case)

2024-10-10 11:30 UTC, GabbasovDinar reviewed
Code LGTM!

2024-10-10 11:30 UTC, GabbasovDinar approved these changes

2024-10-10 13:17 UTC, Aldeigja requested changes

2024-10-10 13:17 UTC, Aldeigja commented on cetmix_tower_server_yaml/readme/USAGE.md
> +- Open the record you would like to export
`- Open the record you would like to import
`

2024-10-10 13:32 UTC, ivs-cetmix commented on cetmix_tower_server_yaml/readme/USAGE.md
> +- Open the record you would like to export
@Aldeigja fixed

2024-10-10 13:44 UTC, GabbasovDinar approved these changes

2024-10-11 08:57 UTC, Aldeigja approved these changes
Functional LGTM

2024-10-11 13:09 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-10-11 13:09 UTC, CetmixGitDrone commented
Hey, thanks for contributing! Proceeding to merge this for you.
Prepared branch [14.0-dev-ocabot-merge-pr-103-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-103-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-10-11 13:11 UTC, merged

2024-10-11 13:11 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at 4bf482c65c63fcd97417a08bfac6ad6ab4b8a317. Thanks a lot for contributing to cetmix. ❤️