[14.0 t3956 cetmix tower server appearance fixes
cetmix/cetmix-tower pull request #104
Opened 2024-10-08 21:00 UTC by Aldeigja

2024-10-08 21:23 UTC, ivs-cetmix requested changes

2024-10-08 21:23 UTC, ivs-cetmix commented on cetmix_tower_server/views/cx_tower_command_view.xml
> +                            string="Command Logs"
Just "Logs" will be enough

2024-10-08 21:23 UTC, ivs-cetmix commented on cetmix_tower_server/views/cx_tower_plan_view.xml
> +                            string="Flight Plan Logs"
Just "Logs" will be enough

2024-10-08 21:23 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_command_log.py
> +                        "Command '%(name)s'<br/> finished successfully",
No need to put <br/> here. Just `Command '%(name)s' finished successfully` as it was before

2024-10-08 21:23 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_command_log.py
> +                        "Command '%(name)s'<br/>"
Same here, pls remove <br/>

2024-10-08 21:23 UTC, ivs-cetmix commented on cetmix_tower_server/views/cx_tower_variable_view.xml
> +                <field name="reference" optional="hide" />
Pls put this field after `name` and make "optional=show"

2024-10-08 21:23 UTC, ivs-cetmix commented on cetmix_tower_server/views/cx_tower_variable_view.xml
> +                <field name="reference" string="Reference" />
No need for `string=` here because it will use the field name by default

2024-10-08 21:23 UTC, ivs-cetmix commented on cetmix_tower_server/views/cx_tower_command_view.xml
> +                <filter
Put this filter right after the "shell command" and rename the filters:

- SSH Command
- Python Code
- File from Template

2024-10-09 11:51 UTC, ivs-cetmix requested changes

2024-10-09 11:51 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_command_log.py
>                          "Command '%(name)s'<br/>"
We should remove <br/> here. Just like it's done in the "Success" message.

2024-10-09 15:23 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-10-09 15:23 UTC, CetmixGitDrone commented
Hey, thanks for contributing! Proceeding to merge this for you.
Prepared branch [14.0-dev-ocabot-merge-pr-104-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-104-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-10-09 15:28 UTC, merged

2024-10-09 15:28 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at 4a836f8da8a3564f1368cc01e8c926a542fc6534. Thanks a lot for contributing to cetmix. ❤️