[FIX] cetmix_tower_server_queue: Fix order of command executions that trigger running other plans
cetmix/cetmix-tower pull request #121
Opened 2024-10-24 10:19 UTC by GabbasovDinar

This commits fixes the following issues:

Steps to reproduce
-------------------

- Create a flight plan that contains another flight plans as commands
- Install cetmix_tower_server_queue
- Run the plan

Expected result
----------------

​- Parent plan commands are executed one after child  flight plan finishes execution
- Command log for commands that run flight plan has a link to the corresponding flight plan log. 
- All fields that are not needed for such command are hidden (code, command)

Current result
--------------

- Child fling plans are queued and executed later
- Main flight plan doesn't wait for child flight plans exectution
- Command log for the command that runs a flight plan doesn't have a link to a flight plan log. 
- 'code' and 'command' fields are displayed

Task: 3996

2024-10-25 08:10 UTC, Aldeigja approved these changes
Functional LGTM

2024-10-25 16:13 UTC, ivs-cetmix requested changes
Code review LGTM.
Regarding commit messages please use the "Before/After" pattern for better traceability:

```
Before this commit
-------------------

Some shit was happening.

After this commit
------------------

This shit isn't happening any longer.
```

2024-10-28 19:04 UTC, ivs-cetmix commented
/ocabot rebase

2024-10-28 19:04 UTC, CetmixGitDrone commented
Congratulations, PR rebased to [14.0-dev](https://github.com/cetmix/cetmix-tower/commits/14.0-dev).

2024-10-29 23:40 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-10-29 23:41 UTC, CetmixGitDrone commented
This PR looks fantastic, let's merge it!
Prepared branch [14.0-dev-ocabot-merge-pr-121-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-121-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-10-29 23:46 UTC, merged

2024-10-29 23:46 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at 1b4d8af81c43ca9c2ca036584e93a9d275ce6ec4. Thanks a lot for contributing to cetmix. ❤️