[IMP] cetmix_tower_server,cetmix_tower_server_notify_backend: Move notification features to new module
cetmix/cetmix-tower pull request #122
Opened 2024-10-25 05:28 UTC by GabbasovDinar

This commit moves all features that use the `web_notify` OCA module from the `cetmix_tower_server` module to the new module.

Task: 4000

2024-10-25 14:25 UTC, ivs-cetmix requested changes
Please check the comments and also add `i18n` directory to the new module

2024-10-25 14:25 UTC, ivs-cetmix commented on cetmix_tower_server_notify_backend/__manifest__.py
> +    "application": True,
This is not an Application

2024-10-25 14:25 UTC, ivs-cetmix commented on cetmix_tower_server_notify_backend/__manifest__.py
> +    "external_dependencies": {
Please remove empty keys

2024-10-25 14:25 UTC, ivs-cetmix commented on cetmix_tower_server_notify_backend/__manifest__.py
> +    "data": [],
Please remove empty keys

2024-10-28 09:08 UTC, ivs-cetmix approved these changes
Code review LGTM

2024-10-28 12:22 UTC, Aldeigja approved these changes
Functional LGTM

2024-10-28 12:33 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-10-28 12:34 UTC, CetmixGitDrone commented
On my way to merge this fine PR!
Prepared branch [14.0-dev-ocabot-merge-pr-122-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-122-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-10-28 12:36 UTC, CetmixGitDrone commented
@ivs-cetmix your merge command was aborted due to failed check(s), which you can inspect on [this commit of 14.0-dev-ocabot-merge-pr-122-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/0d56564030a34f47dbc6ae07e38ce1b62c28b061).

After fixing the problem, you can re-issue a merge command. Please refrain from merging manually as it will most probably make the target branch red.

2024-10-28 12:39 UTC, ivs-cetmix commented
/ocabot rebase

2024-10-28 12:39 UTC, CetmixGitDrone commented
Congratulations, PR rebased to [14.0-dev](https://github.com/cetmix/cetmix-tower/commits/14.0-dev).

2024-10-28 12:59 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-10-28 12:59 UTC, CetmixGitDrone commented
This PR looks fantastic, let's merge it!
Prepared branch [14.0-dev-ocabot-merge-pr-122-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-122-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-10-28 13:02 UTC, merged

2024-10-28 13:02 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at d8d3a9ad4fc152ce6e6c9eac1ed320b852e53f21. Thanks a lot for contributing to cetmix. ❤️