[14.0] [IMP] cetmix_tower_server: UI improvements
cetmix/cetmix-tower pull request #149
Opened 2024-11-27 15:16 UTC by Aldeigja

list of UI improvements introduced in this PR:

* Server - Add "Run Command" and "Run Flight Plan" buttons in the form header.
* Flight plan - fix spaces in the command access warning message.
* Add placeholder to the "Code" field in models. Need to avoid misusage.
* Add archive action to command and flight plan view.
* Hide cofiguration and secrets tab on the server form  from group_u
ser.
* Add tower.server.os​ system variable that returns OS name.

Task: 4083

2024-11-27 15:34 UTC, Aldeigja commented on cetmix_tower_server/models/cx_tower_command.py
> +\n\n\n"""
I'm not sure we really need these guidelines here.

2024-11-27 21:03 UTC, ivs-cetmix requested changes

2024-11-27 21:03 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_command.py
> +DEFAULT_SSH_CODE = """ #Execute any SSH command on the target system
`"""# Execute a shell command using SSH on the remote system`
![image](https://github.com/user-attachments/assets/10e2753c-5612-4197-b53d-0c1da6988fa4)

2024-11-27 21:03 UTC, ivs-cetmix commented on cetmix_tower_server/views/cx_tower_server_view.xml
> +                        string="Execute Flight plan"
`Execute Flight Plan`

2024-11-28 21:42 UTC, Aldeigja commented on cetmix_tower_server/views/cx_tower_server_view.xml
> +                                    />
Members of the group_user don't have access to the server templates and creation of templates and servers. Your comment is not applicable here.

2024-11-29 09:18 UTC, ivs-cetmix requested changes

2024-11-29 09:18 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_command.py
> +DEFAULT_SSH_CODE = """ # Execute any SSH command on the target system
Please remove the trailing whitespace
`""" # Execute any SSH command on the target system`
->
`"""# Execute any SSH command on the target system`

2024-11-29 09:18 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_plan.py
> +                    " to these command(s) to the Flight plan users.",
Please ensure that you want to allow those commands to be tun anyway.

2024-11-29 09:18 UTC, ivs-cetmix commented on cetmix_tower_server/views/cx_tower_server_view.xml
> +                                <group name="test_connection_group">
This button should be available for Manager and Root groups only.
Also we should move it closer to the IP Address Fields
![image](https://github.com/user-attachments/assets/f9be3389-d98c-4566-ad5d-522b1874bb64)

2024-11-29 16:40 UTC, ivs-cetmix commented
/ocabot rebase

2024-11-29 16:41 UTC, CetmixGitDrone commented
Congratulations, PR rebased to [14.0-dev](https://github.com/cetmix/cetmix-tower/commits/14.0-dev).

2024-11-29 22:17 UTC, ivs-cetmix requested changes

2024-11-29 22:17 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_command.py
> +DEFAULT_SSH_CODE = """# Execute any SSH command on the target system
Execute -> Run

2024-12-02 07:26 UTC, Aldeigja commented on cetmix_tower_server/views/cx_tower_server_view.xml
>                      />
> * Add group restrictions to limit access to Manager and Root groups

These buttons don't need any restrictions, they should be accessible for members of group user.

> * Move the buttons closer to the IP Address fields for better UX

In my opinion, the form header is the most proper place for these buttons

2024-12-02 10:43 UTC, ivs-cetmix approved these changes
LGTM

2024-12-02 11:44 UTC, tendil reviewed
Check Review

2024-12-02 11:44 UTC, tendil commented on cetmix_tower_server/views/cx_tower_server_view.xml
> +                <button
Add tab to the 155 line for button

---

<img width="528" alt="Снимок экрана 2024-12-02 в 13 34 14" src="https://github.com/user-attachments/assets/12ed6be2-3ba8-4f32-bd12-a17c963dd6da">

2024-12-02 11:44 UTC, tendil commented on cetmix_tower_server/views/cx_tower_server_view.xml
> +                                <button
Add tab to the 227 line for button

---

<img width="765" alt="Снимок экрана 2024-12-02 в 13 37 49" src="https://github.com/user-attachments/assets/443e8a8f-b001-4b6b-ad69-6c183b718440">

2024-12-02 14:11 UTC, tendil approved these changes
LGTM

2024-12-02 16:00 UTC, CetmixGitDrone commented
This PR has the `approved` label and has been created more than 5 days ago. It should therefore be ready to merge by a maintainer (or a PSC member if the concerned addon has no declared maintainer). 🤖

2024-12-02 19:40 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-12-02 19:40 UTC, CetmixGitDrone commented
What a great day to merge this nice PR. Let's do it!
Prepared branch [14.0-dev-ocabot-merge-pr-149-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-149-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-12-02 19:43 UTC, merged

2024-12-02 19:43 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at a95d056e9eed42e988a5693dfc3c7be886917692. Thanks a lot for contributing to cetmix. ❤️