[14.0][IMP] cetmix_tower_server: Update record deletion flow
cetmix/cetmix-tower pull request #151
Opened 2024-11-28 23:09 UTC by dessanhemrayev

Ensuring complete deletion of data in the Tower and maintaining data integrity by cascading deletion of relevant data, if necessary.

- Delete flight plan -> Delete related lines
- Delete flight plan line -> Delete related line actions
- Delete related line actions -> Delete relate variable values
- Delete flight plan log -> Delete related command logs
- Delete server -> Delete related files, secret_ids  and variable values

Task: 4048

2024-11-28 23:16 UTC, dessanhemrayev commented on cetmix_tower_server/tests/test_server.py
> +        )
good point, thanks)

2024-11-28 23:25 UTC, dessanhemrayev commented on cetmix_tower_server/models/cx_tower_server.py
> +        return super().unlink()
ok, but in this project there is no such method as _close_connections

2024-12-02 19:10 UTC, dessanhemrayev commented on cetmix_tower_server/models/cx_tower_server.py
> +        return super().unlink()
good, thanks

2024-12-03 06:23 UTC, Aldeigja approved these changes
Functional LGTM

2024-12-03 14:04 UTC, ivs-cetmix requested changes
Why not to use `ondelete="cascade"` instead of deleting all related records manually?

2024-12-05 05:27 UTC, Aldeigja approved these changes
Functional LGTM

2024-12-05 16:03 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_file.py
> +    )
_run_auto_pull_files function doesn't depend on servers. It checks files only:

```python
@api.model
    def _run_auto_pull_files(self):
        """
        Run auto sync files
        """
        now = fields.Datetime.now()
        files = self.search(
            [
                ("source", "=", "server"),
                ("auto_sync", "=", True),
                ("sync_date_next", "<=", now),
            ]
        )
        files.download(raise_error=False)
```

2024-12-05 16:03 UTC, ivs-cetmix approved these changes
Code review LGTM

2024-12-05 16:03 UTC, CetmixGitDrone commented
This PR has the `approved` label and has been created more than 5 days ago. It should therefore be ready to merge by a maintainer (or a PSC member if the concerned addon has no declared maintainer). 🤖

2024-12-06 13:32 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-12-06 13:32 UTC, CetmixGitDrone commented
What a great day to merge this nice PR. Let's do it!
Prepared branch [14.0-dev-ocabot-merge-pr-151-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-151-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-12-06 13:38 UTC, merged

2024-12-06 13:38 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at d4b23c16cf318d4c79176bc79fa5e717b4cbcc67. Thanks a lot for contributing to cetmix. ❤️