[REF][IMP] Access Rules for Variables and Values with Tests
cetmix/cetmix-tower pull request #166
Opened 2024-12-23 13:45 UTC by tendil

[REF]
- Refactored existing code to align with PEP8 and Odoo guidelines.
- Improved indentation and formatting in affected files for better readability.

[IMP]
- Added access control by inheriting `cx.tower.access.mixin` in `TowerVariable` and `TowerVariableValue` models.
- Introduced the `access_level` field in the models and views, allowing dynamic control of variable visibility.
- Updated search and form views to include the `access_level` field for better usability.

[NEW]
- Created a new security file `cx_tower_variable_security.xml` to define access rules for `TowerVariable`.
- Updated `cx_tower_variable_value_security.xml` to include refined domain rules for `TowerVariableValue`.

[TEST]
- Updated test `test_variable_value_access` to validate refined access logic.
- Added a new test `test_variable_value_server_subscription` to ensure server subscription-based variable visibility.

Steps to Reproduce
1. Create a new variable and assign it to a server with specific `access_level`.
2. Test visibility of the variable based on user roles (`group_user`, `group_manager`, `group_root`).
3. Validate global and local variable toggling and their visibility to respective roles.
4. Subscribe a user to the server and ensure variable visibility updates dynamically.
5. Run the tests (`test_variable_value_access`, `test_variable_value_server_subscription`) to confirm correct behavior.

File Changes
1. `cx_tower_variable_security.xml`
   - Created a new security file to manage access rules for `TowerVariable`.

2. `cx_tower_variable_value_security.xml`
   - Updated domain rules to dynamically control visibility based on `access_level` and server subscriptions.

3. Models (`TowerVariable`, `TowerVariableValue`)
   - Inherited `cx.tower.access.mixin`.
   - Added `access_level` fields and their logic.

4. Views (`TowerVariable`, `TowerVariableValue`)
   - Updated forms and search views to include `access_level` fields.

5. Tests
   - Refined `test_variable_value_access` to ensure compatibility with new logic.
   - Added `test_variable_value_server_subscription` to validate subscription-based access.

6. General
   - Minor corrections in formatting, indentation, and adherence to Odoo development guidelines.

Task: 4055

2024-12-30 10:11 UTC, ivs-cetmix requested changes
Suppose we run a command as User (access_level==1)  that contains variables with access level Manager (access_levele==2).
We need to ensure that all(!) variable values are rendered properly. No just those with the User access level.

2024-12-30 10:11 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_access_mixin.py
> +    access_level = fields.Selection(
What is this change for?

2025-01-03 14:45 UTC, tendil commented on cetmix_tower_server/models/cx_tower_access_mixin.py
> +    access_level = fields.Selection(
Otherwise, I need to move this field to the `cx.tower.variable` and `cx.tower.variable.value` models. Right?

2025-01-03 19:01 UTC, tendil commented on cetmix_tower_server/models/cx_tower_access_mixin.py
> +    access_level = fields.Selection(
Here I just moved the code upwards (minor refactoring)

2025-01-03 20:50 UTC, tendil commented on cetmix_tower_server/tests/test_variable.py
> +        )
Not relevant to the current task at hand.

2025-01-03 20:53 UTC, tendil commented on cetmix_tower_server/tests/test_variable.py
> +            {"name": "Private Variable", "access_level": "1"}
The use of numbers `("1", "2", "3")` in the code as access levels are not "magic numbers" as they clearly correspond to the values defined in `cx.tower.access.mixin`. These values are already fixed and are part of the standard logic used in other parts of the project. Replacing them with constants does not add much value, as it would create a redundant layer of abstraction and complicate support, especially if the access level changes or new values are added. In this case, using numbers directly keeps the code consistent with existing project standards.

2025-01-03 20:54 UTC, tendil commented on cetmix_tower_server/tests/test_variable.py
> +            {"name": "Private Variable", "access_level": "1"}
The use of numbers ("1", "2", "3") in the code as access levels are not "magic numbers" as they clearly correspond to the values defined in cx.tower.access.mixin. These values are already fixed and are part of the standard logic used in other parts of the project. Replacing them with constants does not add much value, as it would create a redundant layer of abstraction and complicate support, especially if the access level changes or new values are added. In this case, using numbers directly keeps the code consistent with existing project standards.

2025-01-04 09:31 UTC, ivs-cetmix requested changes
1. `access_level` field in the `cx.tower.variable.value` model currently is not used. 
2. Variable values are used in several models, we need to add rules for all of them. Check this PR as a reference: https://github.com/cetmix/cetmix-tower/pull/98/files
3. There is no solution on how a user who is a member of "User" group can render a command or a file that contains variables of "Manager" or "Root" access level.

2025-01-04 09:31 UTC, ivs-cetmix commented on cetmix_tower_server/security/cx_tower_variable_security.xml
> +        <field name="domain_force">[('access_level', 'in', ['2'])]</field>
Manager also has access to records with access level less than 2. Check other models rules for example.

2025-01-04 09:31 UTC, ivs-cetmix commented on cetmix_tower_server/security/cx_tower_variable_value_security.xml
> +                 ('is_global', '=', True),
Let's remove access to global variable values for User. Leave only the ones that belong to his followed servers.

2025-01-04 09:31 UTC, ivs-cetmix commented on cetmix_tower_server/security/cx_tower_variable_value_security.xml
> +                 ('variable_id.access_level', 'in', ['2']),
Manager also has access to records with access level less than 2. Check other models rules for example.

2025-01-04 09:31 UTC, ivs-cetmix commented on cetmix_tower_server/security/cx_tower_variable_value_security.xml
> +                 ('variable_id.access_level', '=', '1'),
You have `access_level` field in the variable value model added by mixin. Why are you checking the variable access level instead?

2025-01-05 12:12 UTC, tendil commented
> 3\. There is no solution on how a user who is a member of "User" group can render a command or a file that contains variables of "Manager" or "Root" access level.

---

Does that mean it needs to be added?

2025-01-05 16:06 UTC, tendil commented on cetmix_tower_server/tests/test_variable.py
> +        # )
Changed

2025-01-05 16:06 UTC, tendil commented on cetmix_tower_server/security/cx_tower_variable_value_security.xml
> +        </record>
Changed

2025-01-05 16:07 UTC, tendil commented on cetmix_tower_server/security/cx_tower_variable_value_security.xml
> +        </record>
Changed

2025-01-05 16:43 UTC, ivs-cetmix commented
> > 3. There is no solution on how a user who is a member of "User" group can render a command or a file that contains variables of "Manager" or "Root" access level.
> 
> @ivs-cetmix Does that mean it needs to be added?

Yes of course. Otherwise variables are barely usable.

2025-01-05 17:02 UTC, ivs-cetmix requested changes

2025-01-05 17:02 UTC, ivs-cetmix commented on cetmix_tower_server/security/cx_tower_variable_value_security.xml
> +                ['&amp;',
No need to add `&` explicitly, because it's the default operator.

2025-01-17 17:12 UTC, ivs-cetmix requested changes

2025-01-17 17:12 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_variable_value.py
> +    def _onchange_variable_id_set_access_level(self):
You should use "compute" with "readonly=False" instead of "onchange" wherever it's possible.

2025-01-17 17:12 UTC, ivs-cetmix commented on cetmix_tower_server/models/cx_tower_variable_value.py
> +    def _check_access_level_consistency(self):
There is the same function in L194, isn't it?

2025-01-17 17:12 UTC, ivs-cetmix commented on cetmix_tower_server/security/cx_tower_variable_value_security.xml
> +                '|',
```
('access_level', '&lt;=', '2'),
'|',
('is_global', '=', True),
('server_id.message_partner_ids', 'in', [user.partner_id.id])
```

2025-01-17 20:35 UTC, closed without merging