[14.0][IMP]cetmix_tower_server: Set server status from command
cetmix/cetmix-tower pull request #90
Opened 2024-09-18 18:08 UTC by DemchukM

Set server status from command

2024-09-18 18:27 UTC, ivs-cetmix requested changes
Please add/update test coverage before submitting the code for review

2024-09-24 21:51 UTC, ivs-cetmix requested changes

2024-10-01 11:56 UTC, ivs-cetmix commented
/ocabot rebase

2024-10-01 11:57 UTC, CetmixGitDrone commented
Congratulations, PR rebased to [14.0-dev](https://github.com/cetmix/cetmix-tower/commits/14.0-dev).

2024-10-07 07:46 UTC, GabbasovDinar requested changes

2024-10-07 07:46 UTC, GabbasovDinar commented on cetmix_tower_server/models/cx_tower_server.py
> +        if need_check_server_status:
Please, don't copy need_check_server_status variable, use `else` operator to set default value
 
```python
        response = None
        need_check_server_status = True

        if command.action == "ssh_command":
            response = self._command_runner_ssh(
                log_record,
                rendered_command_code,
                rendered_command_path,
                ssh_connection,
                **kwargs,
            )
        elif command.action == "file_using_template":
            response = self._command_runner_file_using_template(
                log_record,
                command.file_template_id,
                rendered_command_path,
                **kwargs,
            )
        elif command.action == "python_code":
            response = self._command_runner_python_code(
                log_record,
                rendered_command_code,
                **kwargs,
            )
        else:
            need_check_server_status = False

```

2024-10-07 07:46 UTC, GabbasovDinar commented on cetmix_tower_server/models/cx_tower_server.py
> +            if command.server_status and (
please, use a single `if` clause:
```python
if need_check_server_status and command.server_status and ........
```

2024-10-14 17:59 UTC, GabbasovDinar approved these changes

2024-10-14 21:43 UTC, Aldeigja approved these changes
Functional LGTM

2024-10-14 21:49 UTC, ivs-cetmix approved these changes
LGTM

2024-10-14 22:00 UTC, CetmixGitDrone commented
This PR has the `approved` label and has been created more than 5 days ago. It should therefore be ready to merge by a maintainer (or a PSC member if the concerned addon has no declared maintainer). 🤖

2024-10-25 17:50 UTC, ivs-cetmix commented
/ocabot merge nobump

2024-10-25 17:50 UTC, CetmixGitDrone commented
What a great day to merge this nice PR. Let's do it!
Prepared branch [14.0-dev-ocabot-merge-pr-90-by-ivs-cetmix-bump-nobump](https://github.com/cetmix/cetmix-tower/commits/14.0-dev-ocabot-merge-pr-90-by-ivs-cetmix-bump-nobump), awaiting test results.

2024-10-25 17:53 UTC, merged

2024-10-25 17:53 UTC, CetmixGitDrone commented
Congratulations, your PR was merged at 487e83dc7e3061342fc3c08634f8607f600ee6cd. Thanks a lot for contributing to cetmix. ❤️